// Source: LEFFF 3.4 (Lexique des Formes Fléchies du Français) — INRIA/Alexina
// Generated by scripts/build-dictionary.ts — 451 308 formes fléchies
import words from "./data/lefff-words.json";
import { createSetDictionary, createWordValidatorFromDictionary, type Dictionary } from "./DictionaryService";

const dictionary: Dictionary = createSetDictionary(words);

export const mainDictionary = dictionary;
export const mainValidator = createWordValidatorFromDictionary(dictionary);
