// Primary source: LEFFF 3.4 (Lexique des Formes Fléchies du Français) — INRIA/Alexina
// Supplement: Dicollecte/Hunspell fr_FR (MPL-2.0) — modern loanwords & compounds absent from LEFFF
// Generated by scripts/build-dictionary.ts
import lefff from "./data/lefff-words.json";
import supplement from "./data/supplement-words.json";
import { createSetDictionary, createWordValidatorFromDictionary, type Dictionary } from "./DictionaryService";

const dictionary: Dictionary = createSetDictionary([...(lefff as string[]), ...(supplement as string[])]);

export const mainDictionary = dictionary;
export const mainValidator = createWordValidatorFromDictionary(dictionary);
