// Primary source: LEFFF 3.4 (Lexique des Formes Fléchies du Français) — INRIA/Alexina
// Supplement: Dicollecte/Hunspell fr_FR (MPL-2.0) — modern loanwords & compounds absent from LEFFF
// Generated by scripts/build-dictionary.ts
import { createSetDictionary, type Dictionary } from "./DictionaryService";
import { IS_ENGLISH } from "../language";

let cached: Dictionary | null = null;
let loading: Promise<Dictionary> | null = null;

/**
 * Loads the dictionaries on demand. The draw renders immediately; the word
 * list arrives while the player is still thinking. Concurrent callers share
 * one in-flight load.
 */
export function loadMainDictionary(): Promise<Dictionary> {
  if (cached) return Promise.resolve(cached);
  loading ??= (async () => {
    if (IS_ENGLISH) {
      const words = await import("./data/english-words.json");
      cached = createSetDictionary(words.default);
      return cached;
    }
    const [lefff, supplement] = await Promise.all([
      import("./data/lefff-words.json"),
      import("./data/supplement-words.json"),
    ]);
    cached = createSetDictionary([
      ...(lefff.default as string[]),
      ...(supplement.default as string[]),
    ]);
    return cached;
  })();
  return loading;
}

/** Validates a word. Returns false until the dictionary has loaded. */
export function mainValidator(normalizedWord: string): boolean {
  return cached ? cached.has(normalizedWord) : false;
}

export function isDictionaryReady(): boolean {
  return cached !== null;
}
